server.port: 9090

spring:
  application:
    name: USER-SERVICE
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: user
#    password: password

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    fetch-registry: true
    register-with-eureka: true

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, health, info