server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application.name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, health, info

constant.test.value: "test-a"
