server.port: 8081

spring:
  application:
    name: ITEM-SERVICE

  jpa:
    hibernate.ddl-auto: create-drop

  config.import: # this is highlighted as red, but working normally
    - classpath:/data-init-config.yml
    - classpath:/rabbitmq.yml

  datasource:
    url: jdbc:mysql://localhost:3306/item-db?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: item-user
    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    lease-renewal-interval-in-seconds: 1
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
