server.port: 0

spring:
  application:
    name: COUPON-SERVICE

  jpa:
    hibernate.ddl-auto: create-drop

  config.import:  # this is highlighted as red, but working normally
    - classpath:/data-init-config.yml
    - classpath:/rabbitmq.yml

  datasource:
    url: jdbc:mysql://localhost:3306/coupon-db?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: coupon-user
    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
