
### 주문 리스트 조회
GET http://localhost:8000/orders


### 주문하기
POST http://localhost:8000/orders
Content-Type: application/json

{
  "orderLineRequests": [
    {
      "itemId": 1,
      "quantity": 10
    },
    {
      "itemId": 2,
      "quantity": 1
    }
  ]
}
