version: '3.1'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # AMQP port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
