server.port: 0

spring:
  application:
    name: ORDER-SERVICE

  jpa.hibernate.ddl-auto: create-drop

  config.import: # this is highlighted as red, but working normally
    - classpath:/data-init-config.yml
    - classpath:/rabbitmq.yml

  datasource:
    url: jdbc:mysql://localhost:3306/order-db?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: order-user
    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 1
